const mongoose = require('mongoose'); 


var courseSchema = new mongoose.Schema({
    title:{
        type:String,
        required:true,
        trim:true,
        minlength:3,
        maxlength:350,
    },
    slug:{
        type:String,
        required:true,
        unique:true,
    },
    description:{
        type:String,
        required:true,
        trim:true,
        minlength:3,
        maxlength:5000,
    },
    price:{
        type:Number,
        required:0,
    },
    image:{
        type:String,
        default:""
    },
    category:{
        type:String,
        required:true
    },
    published:{
        type:Boolean,
        default:false
    },
    paid:{
        type:Boolean,
        default:false
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    enrolls:{
        type:Number,
        required:true,
        default:0
    },
    totalHours:{
        type:String,
        required:true,
        default:"0"
    },
    lessons:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Lesson",
        }
    ],
    ratings:[
        {
            stars:Number,
            comment:String,
            postedBy:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"User" 
            }
        }
    ],
    totalRatings:{
        type:Number,
        required:true,
        default:0
    }
},{
    timestamps:true
});

//Export the model
module.exports = mongoose.model('Course', courseSchema);